apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev-backend-deployment
  labels:
    app: rev-backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: IMAGE_NAME
          ports:
            - containerPort: 80
