apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev-backend-deployment
  labels:
    app: rev-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: 222634389464.dkr.ecr.ap-south-1.amazonaws.com/rev-imgs:backend_main_latest_tag
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: backend-env-secret
