apiVersion: v1
kind: Service
metadata:
  name: rev-backend-service
  labels:
    app: rev-backend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
      nodePort: 30080 # NodePort to expose the service externally on this port (within the valid range)
  selector:
    app: rev-backend
